/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "TMVAWrapper.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 


#include <cstdlib>
#include <vector>
#include <iostream>
#include <map>
#include <string>

#include "TFile.h"
#include "TNtuple.h"
#include "TTree.h"
#include "TString.h"
#include "TSystem.h"
#include "TROOT.h"
#include "TStopwatch.h"

#if not defined(__CINT__) || defined(__MAKECINT__)
#include "TMVA/Tools.h"
#include "TMVA/Reader.h"
#endif

//using namespace TMVA;

/* update to parse XML for expected variables
  <Variables NVar="2">
    <Variable VarIndex="0" Expression="x" Label="x" Title="mass" Unit="units" Internal="x" Type="F" Min="-5.79654074e+00" Max="4.99505901e+00"/>
    <Variable VarIndex="1" Expression="alpha" Label="alpha" Title="alpha" Unit="units" Internal="alpha" Type="F" Min="-2.00000000e+00" Max="2.00000000e+00"/>
  </Variables>

*/

ClassImp(TMVAWrapper) 

 TMVAWrapper::TMVAWrapper(const char *name, const char *title, 
                        RooAbsReal& _features, RooAbsReal& _param) :
   RooAbsReal(name,title), 
   features("features","features",this,_features),
   param("param","param",this,_param)
 { 

   TMVA::Tools::Instance();
   reader = new TMVA::Reader( "!Color:!Silent" );    

   // Create a set of variables and declare them to the reader
   // - the variable names MUST corresponds in name and type to those given in the weight file(s) used
   reader->AddVariable( "x", &x);
   reader->AddVariable( "alpha", &alpha);

   // --- Book the MVA methods

   TString dir    = "weights/";
   TString prefix = "TMVARegression";

   // Book method(s)
   TString methodName = "MLP method";
   const TString weightfile = "TMVARegression_alphavary.root_MLP.weights.xml";
   reader->BookMVA( methodName, weightfile ); 
 } 


 TMVAWrapper::TMVAWrapper(const TMVAWrapper& other, const char* name) :  
   RooAbsReal(other,name), 
   features("features",this,other.features),
   param("param",this,other.param)
 { 
   TMVA::Tools::Instance();
   reader = new TMVA::Reader( "!Color:!Silent" );    
      // Create a set of variables and declare them to the reader
   // - the variable names MUST corresponds in name and type to those given in the weight file(s) used
   reader->AddVariable( "x", &x);
   reader->AddVariable( "alpha", &alpha);

   // --- Book the MVA methods

   TString dir    = "weights/";
   TString prefix = "TMVARegression";

   // Book method(s)
   TString methodName = "MLP method";
   const TString weightfile = "TMVARegression_alphavary.root_MLP.weights.xml";
   reader->BookMVA( methodName, weightfile ); 

 } 



 Double_t TMVAWrapper::evaluate() const 
 { 

   x = features.arg().getVal();
   alpha = param.arg().getVal();
   Float_t val = (reader->EvaluateRegression("MLP method"))[0];


   return val ; 
 } 

