/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef TMVAWRAPPER
#define TMVAWRAPPER

#include "RooAbsReal.h"
#include "RooArgList.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooListProxy.h"

#include "TDOMParser.h"
#include "TXMLNode.h"
#include <iostream>
#include "TList.h"
#include "TXMLAttr.h"

#if not defined(__CINT__) || defined(__MAKECINT__)
#include "TMVA/Tools.h"
#include "TMVA/Reader.h"
#endif


/*namespace TMVA {
    class Reader;
}
*/

class TMVAWrapper : public RooAbsReal {
public:
  TMVAWrapper() {} ; 
  //  TMVAWrapper(const char *name, const char *title,
  //	      RooAbsReal& _features, RooAbsReal& _param);
  TMVAWrapper(const TMVAWrapper& other, const char* name=0) ;
  TMVAWrapper(const char *name, const char *title, RooArgList &ral,char weightfile[100]);

  virtual TObject* clone(const char* newname) const { return new TMVAWrapper(*this,newname); }
  inline virtual ~TMVAWrapper() { }


protected:


  RooAbsReal *_rab[10];
  
  int num_features;
  std::vector<TString> names;

  Double_t evaluate() const ;

  char weights[1000];

private:


  void findVariables(TXMLNode *node);
  void getListOfVars(char weights[100]);
  
  TMVA::Reader *reader ;
  mutable Float_t local_features[10];
  Float_t target;

  RooListProxy _actualVars;

  ClassDef(TMVAWrapper,1) // Your description goes here...
};
 
#endif
