/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "CompositeFunctionPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(CompositeFunctionPdf) 

 CompositeFunctionPdf::CompositeFunctionPdf(const char *name, const char *title, 
                        RooAbsReal& _x) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x)
 { 
 } 


 CompositeFunctionPdf::CompositeFunctionPdf(const CompositeFunctionPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x)
 { 
 } 



 Double_t CompositeFunctionPdf::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
//   return x ; 
   return x.arg().getVal();
 } 



 Int_t CompositeFunctionPdf::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const  
 { 
   // LIST HERE OVER WHICH VARIABLES ANALYTICAL INTEGRATION IS SUPPORTED, 
   // ASSIGN A NUMERIC CODE FOR EACH SUPPORTED (SET OF) PARAMETERS 
   // THE EXAMPLE BELOW ASSIGNS CODE 1 TO INTEGRATION OVER VARIABLE X
   // YOU CAN ALSO IMPLEMENT MORE THAN ONE ANALYTICAL INTEGRAL BY REPEATING THE matchArgs 
   // EXPRESSION MULTIPLE TIMES

   // if (matchArgs(allVars,analVars,x)) return 1 ; 
   //   cout << "in analytic integral" <<endl;
   return 1 ; 
 } 



 Double_t CompositeFunctionPdf::analyticalIntegral(Int_t code, const char* rangeName) const  
 { 
   // RETURN ANALYTICAL INTEGRAL DEFINED BY RETURN CODE ASSIGNED BY getAnalyticalIntegral
   // THE MEMBER FUNCTION x.min(rangeName) AND x.max(rangeName) WILL RETURN THE INTEGRATION
   // BOUNDARIES FOR EACH OBSERVABLE x

   assert(code==1) ; 
   //   cout << "in analytic integral" <<endl;
   // return (x.max(rangeName)-x.min(rangeName)) ; 
   return 1. ; 
 } 



