/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SCIKITLEARNWRAPPER2d
#define SCIKITLEARNWRAPPER2d

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#ifndef __CINT__
#include "Python.h"
#endif

#ifndef PyObject_HEAD
struct _object;
typedef _object PyObject;
#endif


class SciKitLearnWrapper2d : public RooAbsReal{
public:
  SciKitLearnWrapper2d() {} ; 
  SciKitLearnWrapper2d(const char *name, const char *title, RooAbsReal& _features, RooAbsReal& _params);
  SciKitLearnWrapper2d(const SciKitLearnWrapper2d& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SciKitLearnWrapper2d(*this,newname); }
  inline virtual ~SciKitLearnWrapper2d() { }

  void RegisterCallBack( PyObject* pyobject );

  Double_t call_eval(){return evaluate();}
  Double_t call_getVal(){return getVal();}

protected:

  virtual Double_t evaluate() const ;

private:
  RooRealProxy features;
  RooRealProxy params ;  

  PyObject* m_callback;
  ClassDef(SciKitLearnWrapper2d,1); // Your description goes here...
};
 
#endif
