/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory    
 * https://docs.python.org/2/extending/embedding.html#pure-embedding          * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "SciKitLearnWrapper.h" 
#include <math.h> 

#ifndef __CINT__
#include "Python.h"
#endif

ClassImp(SciKitLearnWrapper) 

  SciKitLearnWrapper::SciKitLearnWrapper(const char *name, const char *title, 
                       RooAbsReal& _features) :
  RooAbsReal(name,title), 
  features("features","features",this,_features)
 { 
    m_callback=NULL;

 } 


 SciKitLearnWrapper::SciKitLearnWrapper(const SciKitLearnWrapper& other, const char* name) :  
  RooAbsReal(other,name), 
  features("features",this,other.features),
  m_callback(other.m_callback) { 
 } 



 Double_t SciKitLearnWrapper::evaluate() const 
 { 
  // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
  //std::cout << "Hi from C++!" << std::endl;
  char* blah=NULL;
  if(    m_callback==NULL) return 0;

  #ifndef __CINT__
  //PyObject* result = PyObject_CallFunction( m_callback, blah);
  // cout << "result as long " << PyInt_AsLong(result) << endl;
  //cout << "result as double " << PyFloat_AsDouble(result) << endl; 

  //cout << "features.arg().getVal() = " << features.arg().getVal() << endl;

  PyObject* arg = PyFloat_FromDouble(features.arg().getVal());
//  PyObject* result = PyObject_CallObject( m_callback, arg   );
  PyObject* result = PyObject_CallFunctionObjArgs( m_callback, arg , NULL  );
  Py_XDECREF( arg );

  double ret;
  PyArg_Parse((result),"d", &ret);
  //cout << "from parse " << ret << endl;

  Py_XDECREF( result );
  #endif
  return ret ; 
 } 

void SciKitLearnWrapper::RegisterCallBack( PyObject* pyobject )
{
	// see http://root.cern.ch/phpBB3/viewtopic.php?t=2606
	Py_INCREF( pyobject );
	m_callback = pyobject;
}


