/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SCIKITLEARNWRAPPER
#define SCIKITLEARNWRAPPER

#include "TNamed.h"
#ifndef __CINT__
#include "Python.h"
#endif

class SciKitLearnWrapper : public TNamed{
public:
  SciKitLearnWrapper() {} ; 
  SciKitLearnWrapper(const char *name, const char *title);
  SciKitLearnWrapper(const SciKitLearnWrapper& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SciKitLearnWrapper(*this,newname); }
  inline virtual ~SciKitLearnWrapper() { }

  void RegisterCallBack( PyObject* pyobject );

  Double_t evaluate() const ;
  

private:

  PyObject* m_callback;
  ClassDef(SciKitLearnWrapper,1); // Your description goes here...
};
 
#endif
