/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SCIKITLEARNWRAPPER
#define SCIKITLEARNWRAPPER

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

#ifndef __CINT__
#include "Python.h"
#endif

class SciKitLearnWrapper : public RooAbsReal{
public:
  SciKitLearnWrapper() {} ; 
  SciKitLearnWrapper(const char *name, const char *title, RooAbsReal& _features);
  SciKitLearnWrapper(const SciKitLearnWrapper& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SciKitLearnWrapper(*this,newname); }
  inline virtual ~SciKitLearnWrapper() { }

  void RegisterCallBack( PyObject* pyobject );

  Double_t call_eval(){return evaluate();}

protected:

  virtual Double_t evaluate() const ;

private:
  RooRealProxy features ;  

  PyObject* m_callback;
  ClassDef(SciKitLearnWrapper,1); // Your description goes here...
};
 
#endif
